services:
    traefik:
        image: traefik:2.3
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            ferror:
                ipv4_address: 192.168.10.10

    postgresql:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: temporal
            POSTGRES_USER: temporal
        ports:
            - "5432:5432"
        networks:
            - ferror

    temporal:
        image: temporalio/auto-setup:1.6.3
        depends_on:
            - postgresql
            - traefik
        environment:
            - DB=postgresql
            - DB_PORT=5432
            - POSTGRES_USER=temporal
            - POSTGRES_PWD=temporal
            - POSTGRES_SEEDS=postgresql
        ports:
            - "7233:7233"
        labels:
            - "traefik.enable=true"
        networks:
            - ferror

    temporal-admin-tools:
        image: temporalio/admin-tools:1.6.3
        depends_on:
            - temporal
            - traefik
        environment:
            - TEMPORAL_CLI_ADDRESS=temporal:7233
        stdin_open: true
        tty: true
        networks:
            - ferror

    temporal-web:
        image: temporalio/web:1.6.1
        depends_on:
            - temporal
            - traefik
        environment:
            - TEMPORAL_GRPC_ENDPOINT=temporal:7233
            - TEMPORAL_PERMIT_WRITE_API=true
        labels:
            - "traefik.enable=true"
        networks:
            - ferror
        ports:
            - "8088:8088"

    app:
        image: ferror/symfony-image:8.0-grpc
        volumes:
            - ./:/app:delegated
        command: ["make", "run"]
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.symfony.rule=Host(`symfony.malcherczyk.localhost`)"
        depends_on:
            - temporal
            - traefik
        networks:
            - ferror
        environment:
            - "TEMPORAL_CLI_ADDRESS=temporal:7233"

networks:
    ferror:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/24
