version: '3.5'

services:
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    ports:
      - "5432:5432"

  temporal:
    image: temporalio/auto-setup:1.6.3
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    ports:
      - "7233:7233"

  temporal-admin-tools:
    image: temporalio/admin-tools:1.6.3
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true

  temporal-web:
    image: temporalio/web:1.6.1
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - "8088:8088"

  app:
    build: .
    volumes:
      - ./:/app:delegated
    command: ["make", "run"]
    depends_on:
      - temporal
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporal:7233"
