parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

#    Temporal\Client\GRPC\ServiceClient: ~
#
#    Temporal\Client\ServiceClientInterface:
#        factory: ['Temporal\Client\GRPC\ServiceClient', 'create']
#        arguments: ['localhost:7233']
#
#    Temporal\Client\WorkflowClientInterface:
#        class: Temporal\Client\WorkflowClient
#        arguments: ['@Temporal\Client\ServiceClientInterface']
